#!/usr/bin/env python3
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

if len(sys.argv) > 1 and sys.argv[1] == "fix":
    sys.argv.pop(1)
    from fixes.fixer import main
else:
    from audit import main

main()
